// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatchMindAI.Infrastructure.Data;

#nullable disable

namespace PatchMindAI.Infrastructure.Migrations
{
    [DbContext(typeof(PatchMindDbContext))]
    [Migration("20260519025517_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("PatchMindAI.Core.Domain.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CveId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserQuery")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CveId");

                    b.HasIndex("Status");

                    b.ToTable("AnalysisJobs");
                });

            modelBuilder.Entity("PatchMindAI.Core.Domain.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedAssetsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawAgentOutputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationStepsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskJustification")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("RiskScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAtUtc");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("AnalysisResults");
                });
#pragma warning restore 612, 618
        }
    }
}
